# path or URL to sample sheet
# TSV format, 4 required columns: sample_name, fq1, fq2, sample_type(PDX/PDO/patient_tissue)
samples: config/samples.tsv

env:
  # xengsort version2.0.9 container, details see env/README.md  
  xengsort: 'env/xengsort209.sif'
  bwa_mem2: 'env/bwa-mem230.sif'

ref:
  # xengsort index
  xengsortidx: "ref/genomes/xengsortidx_grcm38_grch38/xengsortidx"
  # known sites used for gatk_bqsr
  known_sites:
    - "/cluster/tools/data/genomes/human/GRCh38/iGenomes/Annotation/GATKBundle/dbsnp_146.hg38.vcf.gz"
    - "/cluster/tools/data/genomes/human/GRCh38/iGenomes/Annotation/GATKBundle/Mills_and_1000G_gold_standard.indels.hg38.vcf.gz"
    - "/cluster/tools/data/genomes/human/GRCh38/iGenomes/Annotation/GATKBundle/1000G_phase1.snps.high_confidence.hg38.vcf.gz"
  # Panel of Normals (PoN)
  pon: "/cluster/tools/data/genomes/human/GRCh38/iGenomes/Annotation/GATKBundle/1000g_pon.hg38.vcf.gz"
  # GnomAD AF-only
  gnomad: "/cluster/tools/data/genomes/human/GRCh38/iGenomes/Annotation/GATKBundle/af-only-gnomad.hg38.vcf.gz"

ref_index:
  # reference genome for human genome, GRCh38
  genome: "ref/genomes/human/hg38/resources_broad_hg38_v0_Homo_sapiens_assembly38.fasta"
  # reference genome chr name and length
  genome_length: "ref/genomes/human/hg38/resources_broad_hg38_v0_Homo_sapiens_assembly38.genome"
  # reference flat file
  refFlat: "ref/genomes/human/hg38/references_hg38_v0_GRCh38_gencode.v27.refFlat.txt"
  # Path to bwa-mem2 index. 
  # If missing, workflow will run bwa-mem2 index to generate genome.fa.["0123"|"amb"|"ann"|"bwt.2bit.64"|"pac"]
  bwa_mem2_index: "ref/genomes/human/hg38/resources_broad_hg38_v0_Homo_sapiens_assembly38.fasta.0123"

cnv:
  # target region
  target_bed: "ref/genomes/human/WES_target/SureSelectXT_HS_Human_All_Exon_V8_S33266340_Covered.bed"

